version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ../symfony:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: ./php
    container_name: symfony_php
    volumes:
      - ../symfony:/var/www/html
    environment:
      - SYMFONY_ENV=dev

  db:
    image: mysql:8.0
    container_name: symfony_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
